### ISSUE TITLE
Ajustar responsividade da tela de cadastro de usuário.

### ISSUE THREAD

**Issue by ChristoferLv** [Plataforma-29-de-abril/29-april-frontend#4]

**Comment by Alessandro-Neves** [comment]
O Layout mobile está ok, porém o botão de cadastro fica acessivel mesmo sem preencher os campos obrigatórios.
Ao clicar no botão de cadastro sem o campos preenchidos fica em loop infinito.

![Screenshot from 2024-01-09 02-27-07](https://github.com/Plataforma-29-de-abril/29-april-frontend/assets/76932488/e69c3223-d0a4-4bb0-b33b-af4c490e2b46)
